name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run lint
        run: |
          cd starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and tag Docker image
        run: |
          cd starter/backend
          docker build -t 333452229479.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }} .
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 333452229479.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
      - name: Update Kubernetes manifests with kustomize
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=333452229479.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}
      - name: Deploy to Kubernetes
        run: |
          cd starter/backend/k8s
          kustomize build | kubectl apply -f -
